### ISSUE TITLE
After new installation Salt throws exception SaltClientError

### ISSUE THREAD

**Issue by florianb** [martinrusev/amon-issues#27]
After new installation Salt throws exception SaltClientError: `Could not access /var/cache/salt. Path does not exist`, the preceding DEBUG-messages may also be relevant.

From `amonapp.log`:

    [30/Sep/2015 16:06:16] DEBUG [salt.config:866] Missing configuration file: /etc/salt/master
    [30/Sep/2015 16:06:16] DEBUG [salt.config:866] Missing configuration file: /root/.saltrc
    [30/Sep/2015 16:06:16] ERROR [salt.log.setup:713] An un-handled exception was caught by salt's global exception handler:
    SaltClientError: Could not access /var/cache/salt. Path does not exist.
    Traceback (most recent call last):
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 315, in execute
        self._wrap_coverage(self._wrap_profiling, self._execute)
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 250, in _wrap_coverage
        runner(*args)
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 282, in _wrap_profiling
        runner(*args)
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 361, in _execute
        return self.execute_interpreter()
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 371, in execute_interpreter
        self.execute_content(name, content)
      File "/opt/amon/amon.pex/.bootstrap/_pex/pex.py", line 401, in execute_content
        exec_function(ast, globals())
      File "<exec_function>", line 4, in exec_function
      File "/opt/amon/pex-manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/root/.pex/install/Django-1.7.10-py2.py3-none-any.whl.69f1c41e7252e7e9f4e1d93db65a1376ba3dec2b/Django-1.7.10-py2.py3-none-any.whl/django/core/management/__init__.py", line 385, in execute_from_command_line
        utility.execute()
      File "/root/.pex/install/Django-1.7.10-py2.py3-none-any.whl.69f1c41e7252e7e9f4e1d93db65a1376ba3dec2b/Django-1.7.10-py2.py3-none-any.whl/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/root/.pex/install/Django-1.7.10-py2.py3-none-any.whl.69f1c41e7252e7e9f4e1d93db65a1376ba3dec2b/Django-1.7.10-py2.py3-none-any.whl/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)
      File "/root/.pex/install/Django-1.7.10-py2.py3-none-any.whl.69f1c41e7252e7e9f4e1d93db65a1376ba3dec2b/Django-1.7.10-py2.py3-none-any.whl/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)
      File "/root/.pex/install/django_kronos-0.7-py2-none-any.whl.fd0b2783d55141a4b11950ea6ade1647a491c6b0/django_kronos-0.7-py2-none-any.whl/kronos/management/commands/showtasks.py", line 10, in handle
        kronos.load()
      File "/root/.pex/install/django_kronos-0.7-py2-none-any.whl.fd0b2783d55141a4b11950ea6ade1647a491c6b0/django_kronos-0.7-py2-none-any.whl/kronos/__init__.py", line 31, in load
        import_module(p)
      File "/root/.pex/install/Django-1.7.10-py2.py3-none-any.whl.69f1c41e7252e7e9f4e1d93db65a1376ba3dec2b/Django-1.7.10-py2.py3-none-any.whl/django/utils/importlib.py", line 46, in import_module
        __import__(name)
      File "/opt/amon/amon/apps/notifications/cron.py", line 5, in <module>
        from amon.apps.remote.execute import execute_commands
      File "/opt/amon/amon/apps/remote/execute.py", line 4, in <module>
        from amon.apps.remote.utils import AmonSaltClient
      File "/opt/amon/amon/apps/remote/utils.py", line 125, in <module>
        amon_salt_client = AmonSaltClient()
      File "/opt/amon/amon/apps/remote/utils.py", line 14, in __init__
        self.client = salt.client.LocalClient()
      File "/root/.pex/install/salt-2015.5.3-py2-none-any.whl.ec95932ca397cbca4517697a0994312234e4ae53/salt-2015.5.3-py2-none-any.whl/salt/client/__init__.py", line 130, in __init__
        self.key = self.__read_master_key()
      File "/root/.pex/install/salt-2015.5.3-py2-none-any.whl.ec95932ca397cbca4517697a0994312234e4ae53/salt-2015.5.3-py2-none-any.whl/salt/client/__init__.py", line 155, in __read_master_key
        self.skip_perm_errors)
      File "/root/.pex/install/salt-2015.5.3-py2-none-any.whl.ec95932ca397cbca4517697a0994312234e4ae53/salt-2015.5.3-py2-none-any.whl/salt/utils/verify.py", line 390, in check_path_traversal
        raise SaltClientError(msg)
    SaltClientError: Could not access /var/cache/salt. Path does not exist.

**Comment by florianb** [comment]
Interestingly the same error appeared during the installation:

    * Installing Amon

    Reading package lists... Done
    Building dependency tree        
    Reading state information... Done
    Building data structures... Done 
      Vormals nicht ausgewähltes Paket amon-company wird gewählt.
    (Lese Datenbank ... 119200 Dateien und Verzeichnisse sind derzeit installiert.)
    Entpacken von amon-company (aus amon.deb) ...
    amon-company (1:4.2.5) wird eingerichtet ...
     Adding system startup for /etc/init.d/amon ...
       /etc/rc0.d/K20amon -> ../init.d/amon
       /etc/rc1.d/K20amon -> ../init.d/amon
       /etc/rc6.d/K20amon -> ../init.d/amon
       /etc/rc2.d/S20amon -> ../init.d/amon
       /etc/rc3.d/S20amon -> ../init.d/amon
       /etc/rc4.d/S20amon -> ../init.d/amon
       /etc/rc5.d/S20amon -> ../init.d/amon
    DEBUG Missing configuration file: /etc/salt/master
    DEBUG Missing configuration file: /root/.saltrc
    ERROR An un-handled exception was caught by salt's global exception handler:
    SaltClientError: Could not access /var/cache/salt. Path does not exist.
    Traceback (most recent call last):
    ...

**Comment by florianb** [comment]
Installation happens on a

    Linux version 3.18.9-x86_64-jb1 ([...]) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) )

**Comment by martinrusev** [comment]
Hi @florianb,

i should write a check for this error. For security reasons Salt is installed, but not automatically configured. To fix this: 

```
sudo cp /opt/amon/salt-master.yml /etc/salt/master
/etc/init.d/salt-master restart
```

Also here (https://www.amon.cx/docs/remote-execution/#remote-execution-gettingstarted)

**Comment by florianb** [comment]
Hi Martin, thanks a lot - i did currently not plan to use the remote-execution. Maybe it's possible to prevent the error by setting a place-holder-configuration up, which does not allow the remote execution. Otherwise the salt-stack should probably not being started?

**Comment by martinrusev** [comment]
@florianb, I will include that in the next update - will make the SaltStack install optional

**Comment by florianb** [comment]
@martinrusev - thanks again. Copying the `salt-master.yml` didn't resolve the problem by the way. I'm trying to investigate the problem.

**Comment by martinrusev** [comment]
@florianb Sent you an email, there is a faster way to resolve this

**Comment by florianb** [comment]
:+1:
